import:
- logstash-plugins/.ci:travis/travis.yml@1.x

jobs:
  include:
    - stage: Integration
      env: ELASTIC_STACK_VERSION=main SNAPSHOT=true INTEGRATION=true
    - env: ELASTIC_STACK_VERSION=8.future SNAPSHOT=true INTEGRATION=true
    - env: ELASTIC_STACK_VERSION=8.next SNAPSHOT=true INTEGRATION=true
    - env: ELASTIC_STACK_VERSION=8.current SNAPSHOT=true INTEGRATION=true
    - env: ELASTIC_STACK_VERSION=8.previous SNAPSHOT=true INTEGRATION=true
    - env: ELASTIC_STACK_VERSION=7.current SNAPSHOT=true INTEGRATION=true
    - env: ELASTIC_STACK_VERSION=8.current INTEGRATION=true
    - env: ELASTIC_STACK_VERSION=8.previous INTEGRATION=true
    - env: ELASTIC_STACK_VERSION=7.current INTEGRATION=true
