import:
- logstash-plugins/.ci:travis/travis.yml@1.x

jobs:
  include:
    - stage: Integration
      env: INTEGRATION=true ELASTIC_STACK_VERSION=7.current
    - env: INTEGRATION=true ELASTIC_STACK_VERSION=8.previous
    - env: INTEGRATION=true ELASTIC_STACK_VERSION=8.current
    - env: INTEGRATION=true SNAPSHOT=true ELASTIC_STACK_VERSION=7.current
    - env: INTEGRATION=true SNAPSHOT=true ELASTIC_STACK_VERSION=8.previous
    - env: INTEGRATION=true SNAPSHOT=true ELASTIC_STACK_VERSION=8.current
    - env: INTEGRATION=true SNAPSHOT=true ELASTIC_STACK_VERSION=8.next
    - env: INTEGRATION=true SNAPSHOT=true ELASTIC_STACK_VERSION=8.future
    - env: INTEGRATION=true SNAPSHOT=true ELASTIC_STACK_VERSION=main
