import:
- logstash-plugins/.ci:travis/travis.yml@1.x

jobs:
  include:
    - stage: Integration
      env: ELASTIC_STACK_VERSION=8.x SNAPSHOT=true INTEGRATION=true
    - env: ELASTIC_STACK_VERSION=7.x SNAPSHOT=true INTEGRATION=true
    - env: ELASTIC_STACK_VERSION=7.x INTEGRATION=true
    - env: ELASTIC_STACK_VERSION=6.x INTEGRATION=true
