version: '3'

# Common base configuration for setting up Logstash to install and test this plugin.
# This docker-compose.yml does not provide a command for the `logstash` service, and should not
# be used without one of the relevant `docker-compose.override.yml`.
services:
  logstash:
    build:
      context: ../../
      dockerfile: .ci/common/logstash.Dockerfile
      args:
        - ELASTIC_STACK_VERSION=$ELASTIC_STACK_VERSION
        - TEST_MODE=$TEST_MODE
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      LOGSTASH_SOURCE: 1
    tty: true
