version: '3'

# provides additional services and overrides common configuration for integration tests.
# SEE: .ci/docker-setup.sh and .ci/docker-run.sh with TEST_MODE=integration
services:
  logstash:
    build:
      args:
        - TEST_MODE=$TEST_MODE # extra argument

    command: /usr/share/plugins/plugin/.ci/integration/run.sh
    tty: true
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: "rabbitmq"
  rabbitmq:
    image: rabbitmq:latest
    hostname: rabbit
    ports:
      - "15672:5672"
